# Classes and Objects
* Classes are blueprint of objects.They are generic and conceptual.
* Objects are implementation of class. They are specific and actual.



In [1]:
#syntax of creating a class
class Car():  #class is a keyword, car is user defined name given to the class ,
    #parenthesis are optional. 
    #parenthesis will be used at the time of inheritance. 
    #data members/ physical attributes
    wheels=4
    max_speed=200
    #member methods/functions   #here we need to write self in each of the function/method of the class
    #self means the object, we use self for self.wheels which means wheels of the object of the car 
    #we have created c1 object of the car in the next cell. here self.wheels means c1.wheels
    #c1.wheels means wheels of c1. so in all the functions self will be repalced by c1
    def __init__(self,w,ms): # special type of member method, which is constructor
        # constructor is executed at the time of object creation to give default/initial properties
        # to the object
        self.wheels=w           
        self.max_speed=ms
    def get_details(self):
        print("wheels: ",self.wheels,"\nspeed: ",self.max_speed)
    def set_details(self,w,ms):
        self.wheels = w
        self.max_speed = ms

In [1]:
a = 5
print(type(a))

<class 'int'>


In [2]:
#creating an object 'c1'of the class Car
c1=Car(4,250) # pass the default values here, __init__ this function would take these values
#calling get_details function with the help of .operator
c1.get_details()

wheels:  4 
speed:  250


In [3]:
c1.set_details(5,400)
c1.get_details()

wheels:  5 
speed:  400


In [4]:
c2 = Car(6,600) # default values through construtor
c2.get_details()

wheels:  6 
speed:  600


In [5]:
c2.set_details(8,760)
c2.get_details()

wheels:  8 
speed:  760


In [2]:
class Groceryshop:
    #data members 
    eggs=100
    milkbags=50
    #member methods- functions
    #constructor
    def __init__(self,eggs,milkbags):
        self.eggs=eggs
        self.milkbags=milkbags  #(self)-it carries the location(memory addr) of the object which calls the funtion
    def buy(self):
        eggs= int(input('how many eggs do you want to buy?   \n '))
        milkbags= int(input('how many milk bags you want to buy?  \n'))
        self.eggs=eggs
        self.milkbags =milkbags  
        print('customer has bought ',self.eggs, 'eggs and',self.milkbags, 'milk bags.')
    def stock(self):
        print(self)
        print('the current stock is \n1. eggs:',self.eggs,'\n2. milk bags:',self.milkbags)
    
    

In [6]:
#Object of the class
g = GroceryShop(200,100)
g.stock()
s = GroceryShop(100,20)
s.stock()

The curent stock is 
1. Eggs:  200 
2. Milk Bags:  100
The curent stock is 
1. Eggs:  100 
2. Milk Bags:  20


In [7]:
# learning management system
#let's suppose it can have 3 classes
#learner 
#trainer
#courses

In [16]:
#let's create class for all
class Learner():
    pass
class Trainer():
    pass
class Courses():
    pass

In [17]:
#now we need to have data members/physical attributes for all these classes 
class Learner():
    #here we write the data member, we will declare variables with default values
    name=''
    email=''
    mobile_no=''
class Trainer():
    name=''
    email=''
    mobile_no=''
class Courses():
    course_name=''
    course_fee=0
    course_duration=''    

In [18]:
#let's create objects
ramesh = Learner()
ram = Trainer()
Data_Associate = Courses()

In [19]:
#let us give values to the data members of these objects
ramesh.name='ramesh'
ramesh.mobile_no='99934325025'
ramesh.email='ramesh@gmail.com'

ram.name='ram'
ram.email='ram@gamail.com'
ram.mobile_no='9483922021'

Data_Associate.course_name='data_associate'
Data_Associate.course_fee=70000
Data_Associate.course_duration='ok'


In [20]:
#now let us see how to display the object values
print(ramesh.name)
print(ramesh.mobile_no)
print(ramesh.email)

print(ram.name)
print(ram.email)
print(ram.mobile_no)

print(Data_Associate.course_name)
print(Data_Associate.course_fee)
print(Data_Associate.course_duration)

ramesh
99934325025
ramesh@gmail.com
ram
ram@gamail.com
9483922021
data_associate
70000
ok


In [21]:
#now let us create member functions/methods also
class Learner():
    #here we write the data member, we will declare variables with default values
    name=''
    email=''
    mobile_no=''
    #member methods
    def set_details(self,n,em,mob):
        self.name=n
        self.email=em
        self.mobile_no=mob
        
    def get_details(self):
        print(self.name)
        print(self.email)
        print(self.mobile_no)
        
class Trainer():
    name=''
    email=''
    mobile_no=''
    
    #member methods
    def set_details(self,n,em,mob):
        self.name=n
        self.email=em
        self.mobile_no=mob
        
    def get_details(self):
        print(self.name)
        print(self.email)
        print(self.mobile_no)
        
        
class Courses():
    course_name=''
    course_fee=0
    course_duration=''


    

In [22]:
#let us try to use member methods
ramesh=Learner()
ramesh.set_details("ramesh","940434034","ramesh@gmail.com")
ramesh.get_details()

ramesh
940434034
ramesh@gmail.com


In [23]:
def name_course():
    def local_func():
        name="python"
    def non_local():
        nonlocal name
        name="python programming"
    def global_func():
        global name
        name="data science"
    name="name_cource"
    print(name)
    local_func()
    print(name)
    non_local()
    print(name)
    global_func()
    print(name)
name_course()
print(name)
    

name_cource
name_cource
python programming
python programming
data science


In [24]:
class python:
    def func():
        print("hello world")

In [3]:
class DA:
    def __init__(self,name):
        self.name=name
    def func(self):
        print("this function is called")
x=DA("associate")
x.name
x.func()

this function is called


In [26]:
class notebook:
    pages=200
    name="history"
    label="standard book"

In [27]:
example_instance=notebook()
print(example_instance.pages)
print(example_instance.name)
print(example_instance.label)


200
history
standard book


In [28]:
class birthdayboy:
    name="deepak"
    age=21
things=birthdayboy()
print(things.name)
print(things.age)


deepak
21


In [4]:
class birthdaygirl:
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def birthday(self):
        self.birthday+=1
me=birthdaygirl('meena',21)
print(me.age)

me.birthday()

print(me.age)

21


TypeError: unsupported operand type(s) for +=: 'method' and 'int'

In [30]:
class LMS():
    #Data Members - currently there are no data members
    #Member Methods
    def details(self): #call it as local function --> local to the class --> can be accessed only through the objects of the class
        print("This is LMS 1.0")

dhinchakpooja='....'
#Function -- laymann's term call it as normal function
def details():
    dhinchakpooja = "flop"
    print("this is fake....")
    print(dhinchakpooja)
details() # just look here, this can be called just by it's name, while the class function can be called as objectname.functionname
print(dhinchakpooja)

this is fake....
flop
....


In [31]:
#How to create an object of this class?
lms1 = LMS()
#This is how you can create an object of the class LMS()

In [32]:
# Aftet you create an object of any class, then you can use the data members and member function of the class
# How to use the member menthod details()
lms1.details()

This is LMS 1.0


In [33]:
# Similarly you can create multiple number of objects
lms2 = LMS()
lms3 = LMS()
# and each of the objects will get their member functions from the class LMS()
# let's call the function with the object
lms2.details()
lms3.details()

This is LMS 1.0
This is LMS 1.0


In [34]:
#Abstraction - hiding the implementation details, what will happen - you know, how it will happen - you don't know
class LMS():
    #Data Members
    lms_name='LMS 1.0'
    is_member = False
    #Member Methods
    def membership_status(self,fee):
        self.fee=fee
        if(self.fee=='paid'):
            self.is_member = True
        print("Your membership status is ",self.is_member)

In [35]:
ramesh = LMS()

In [37]:
fee_status = input("You fee status is paid/unpaid: ")
ramesh.membership_status(fee_status)

You fee status is paid/unpaid: paid
Your membership status is  True


In [ ]:
#Ramesh knows the he would get membership status, but hee is not aware that how will he get it (or how the internal process will give him the results)
# Thus this is abstraction.

In [ ]:
#Inheritance
class Person():
    #we would use the constructor to initialize the data members
    def __init__(self, name, age):
        self.name = name
        self.age = age #name and age become the data member

In [ ]:
manoj = Person("Manoj", 26)
print(manoj.name,"\n",manoj.age)

In [ ]:
class Student(Person):
    def __init__(self,rollno,clas,name,age):
        self.rollno = rollno
        self.clas = clas
        Person.__init__(self,name,age)

In [ ]:
s1 = Student(22,'x','Harjinder', 32)

In [ ]:
print(s1.name,s1.age,s1.clas,s1.rollno)

In [ ]:
#classes and object - i had explained them and they know previously also
#oops concept (APIE) - they know this aswell
#activity to be taken 
#individual/group


In [ ]:
# Encapsulation - watermelon, plum pudding, capsule
class Mobile():
    #Data Members
    brand = "b1"
    price = 99999999
    model_no = 'v1'
    #Member Methods
    def get_details(self):
        print("Brand: ", self.brand, "\nPrice: ",self.price,"\nModel Number: ", self.model_no)
    def set_details(self,b,p,m):
        self.brand = b
        self.price = p
        self.model_no = m

In [ ]:
#Above is an example of Encapsulation, 
#which means as soon as you create a class it is encapsulating data memebers and member methods.

In [ ]:
# Polymorphism - one entity has multiple forms
# let us try with built-in functions
l = [1,2,3,"Pen"]
print(l)
name = "IndeedInspiring"
print(name)
# Here print is one function having many forms, 1 form handles the list data types and another 
# handles the string

In [ ]:
#len is behaving differently with string and list
print(len(l))
print(len(name))

In [ ]:
#Polymorphism with Inheritance
class Country():
    def get_details(self):
        print("This is a detailed version of Country Guide.")
class India(Country):
    def get_details(self):
        print("India is a great Country!!!")

In [ ]:
c1 = Country()
c2 = India()
# put the objects into a list
l = [c1,c2]
for c in l:
    c.get_details()

In [6]:
#NUMPY -->> NUMBER + PYTHON
# importing a liabrary
import numpy as np

In [15]:
# we create an array 
a = np.array([[3,6,5,8],[12,13,15,19]])
print(a)
print(type(a))
print(a[0])

[[ 3  6  5  8]
 [12 13 15 19]]
<class 'numpy.ndarray'>
[3 6 5 8]


In [30]:
b = np.array([[5,6,19],[10,13,16]])
print(b.shape)
print(b.ndim)
print(b)

(2, 3)
2
[[ 5  6 19]
 [10 13 16]]


In [42]:
# we want to create 1 dimension array  everytime it will come as (1,)(3,)(7,)
c = np.array([4])
print(c.shape)
print(c.ndim)

(1,)
1


In [43]:
#we want to create 2 dimension array 
d = np.array([[4,5],[9,3]])
print(d.shape)
print(d.ndim)

(2, 2)
2


In [46]:
# we want to create 3 dimension array
f = np.array([[[5,6],[59,7]]])
print(f.shape)
print(f.ndim)

(1, 2, 2)
3


In [61]:
#create an array having dimension 3 and shape as (3,2,1)
arr = np.array([[[8],[9]],[[8],[9]],[[8],[9]]])
print(arr.shape)
print(arr.ndim)

(3, 2, 1)
3
